### PR TITLE
Add @ic-reactor/react

### PR DESCRIPTION
**Pull request by b3hr4d**
This pull request add `@ic-reactor/react` library, and some small changes.
Would be great if you keep it even in separate branch!

### Dependency Updates:
* Added `@ic-reactor/react` library to `package.json`. 
* Removed `@tanstack/react-query` from `package.json`.

### Configuration Changes:
* Added a new `.prettierrc` configuration file to enforce code formatting rules.
* Removed DFX canister environment variables from the `.env` file.

### Documentation Updates:
* Added `ic-reactor/react` to the list of dependencies in the `README.md` file.

### CODE REVIEW

**Comment by kristoferlund** [comment]
Great, thanks for the PR! Yeah, merging it to a separate branch is a good idea, to let the dev choose their "flavour".

Some feedback:

* How does `ic-reactor` deal with caching, refetching, etc? I believe it is good practice to encapsulate your IC calls in hooks which means you can reuse them in other components. Therefore I suggest moving the `useQueryCall` to the `useGreet` hook like I had set it up. 
* Remove `.prettierrc`. Default settings should be used for a template repository. I have now formatted the codebase using Prettier.

**Comment by b3hr4d** [comment]
Thank you for the feedback! Here's a detailed response:

### Caching, Refetching, and Reusability:
The `@ic-reactor/react` library uses `zustand` at its core for state management. This ensures that data is cached as long as:  
1. The arguments for the query haven't changed.  
2. The user explicitly calls the `call` or `refetch` functions.  
3. A `refetchInterval` is set for automatic updates.  

For example:  
```typescript
const { data, error, loading } = useQueryTodo({
  functionName: "getAllTodos",
  args: [],
  refetchOnMount: true,
  refetchInterval: 5000,
});
```

This setup makes the caching and cross-component reusability of queries a built-in feature of the library.  

That said, encapsulating calls in hooks, like your `useGreet` example, is also an excellent idea for better abstraction and modularity. I highly recommend using a context provider pattern, which integrates seamlessly with `@ic-reactor/react`. Here's an example:  
```typescript
import { createActorContext } from "@ic-reactor/react"
import { canisterId, idlFactory, todo } from "declarations/todo"

export const {
  ActorProvider: TodoActorProvider,
  useQueryCall: useQueryTodo,
  useUpdateCall: useUpdateTodo
} = createActorContext<typeof todo>({
  idlFactory,
  canisterId,
  withDevtools: true // working with redux dev tools!
})
```

### Prettier Configuration:
I added the `.prettierrc` file to align with the existing style in the codebase and ensure consistency. However, I understand your point about keeping default settings for a template repository. Feel free to remove the file if it's unnecessary.  

Let me know if there's anything else you'd like me to adjust!

**Comment by kristoferlund** [comment]
Thanks @b3hr4d! I will have a look and merge to a separate branch in the beginning of the coming week. I'll add info to main branch README as well, letting folks know about this option.

**Comment by kristoferlund** [comment]
@b3hr4d I removed the `.prettierrc` to revert to default settings and then merged with the `ic-reactor` branch. 

`ic-reactor` looks really nice, would like to take a closer look soon!

**Comment by b3hr4d** [comment]
Thank you so much for merging and for taking a look at `ic-reactor`! 🎉 I'm really glad you like it so far.  

Whenever you have time to explore it further, I’d love to hear your insights and suggestions for improvement. Feedback is always welcome to make it even better for everyone!  

Feel free to reach out if you have any questions or need help integrating it into your projects. 😊

**Comment by kristoferlund** [comment]
Also added link in main branch readme.

**Pull request merged**
